name: tour_guide_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0-246.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_screenutil: ^5.9.3
  dartz: ^0.10.1
  logger: ^2.6.0
  http: ^1.4.0
  flutter_svg: ^2.2.0
  device_info_plus: ^11.5.0
  like_button: ^2.0.5
  pin_code_fields: ^8.0.1
  flutter_localization: ^0.3.3
  image_picker: ^1.1.2


  #state management
  flutter_bloc: ^9.1.1

  #comparing dart objects
  equatable: ^2.0.7

  #service locator
  get_it: ^8.0.3

  #dateFormat
  intl: ^0.20.2

  flutter_localizations:
    sdk: flutter

  #Database
  shared_preferences: ^2.5.3
  floor: ^1.5.0

  #make request to api 
  retrofit: ^4.4.2

  #create random ID
  uuid: ^4.5.1
  
  pull_to_refresh: ^2.0.0
  loading_animation_widget: ^1.3.0
  persistent_bottom_nav_bar_v2: ^6.1.0
  dropdown_button2: ^2.3.9


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: '>=8.0.0 <10.0.0'
  floor_generator: ^1.4.2
  build_runner: ^2.3.3

flutter:

  uses-material-design: true
  generate: true

  assets:
  - assets/images/
  - assets/icons/

  fonts:
    - family: Inter-Thin
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Thin.ttf
    - family: Inter-ExtraLight
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-ExtraLight.ttf
    - family: Inter-Light
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Light.ttf
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Medium.ttf
    - family: Inter-SemiBold
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-SemiBold.ttf
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Bold.ttf
    - family: Inter-ExtraBold
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-ExtraBold.ttf
    - family: Inter-Black
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Black.ttf


