name: tour_guide_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0-246.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_screenutil: ^5.9.3
  dartz: ^0.10.1
  logger: ^2.6.0
  http: ^1.4.0
  flutter_svg: ^2.2.0
  device_info_plus: ^11.5.0
  like_button: ^2.0.5
  pin_code_fields: ^8.0.1
  flutter_localization: ^0.3.3
  image_picker: ^1.1.2


  #state management
  flutter_bloc: ^9.1.1

  #comparing dart objects
  equatable: ^2.0.7

  #service locator
  get_it: ^8.0.3

  #dateFormat
  intl: ^0.20.2

  flutter_localizations:
    sdk: flutter

  #Database
  shared_preferences: ^2.5.3
  floor: ^1.5.0

  #make request to api 
  retrofit: ^4.4.2

  #create random ID
  uuid: ^4.5.1
  
  pull_to_refresh: ^2.0.0
  loading_animation_widget: ^1.3.0
  persistent_bottom_nav_bar_v2: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: '>=8.0.0 <10.0.0'
  floor_generator: ^1.4.2
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
  - assets/images/
  - assets/icons/
  - assets/lang/

  fonts:
    - family: NotoSans-Thin
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Thin.ttf
    - family: NotoSans-ThinItalic
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-ThinItalic.ttf
    - family: NotoSans-ExtraLight
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-ExtraLight.ttf
    - family: NotoSans-ExtraLightItalic
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-ExtraLightItalic.ttf
    - family: NotoSans-Light
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Light.ttf
    - family: NotoSans-LightItalic
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-LightItalic.ttf
    - family: NotoSans-Regular
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Regular.ttf
    - family: NotoSans-Italic
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Italic.ttf
    - family: NotoSans-Medium
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Medium.ttf
    - family: NotoSans-MediumItalic
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-MediumItalic.ttf
    - family: NotoSans-SemiBold
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-SemiBold.ttf
    - family: NotoSans-SemiBoldItalic
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-SemiBoldItalic.ttf
    - family: NotoSans-Bold
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Bold.ttf
    - family: NotoSans-BoldItalic
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-BoldItalic.ttf
    - family: NotoSans-ExtraBold
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-ExtraBold.ttf
    - family: NotoSans-ExtraBoldItalic
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-ExtraBoldItalic.ttf
    - family: NotoSans-Black
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-Black.ttf
    - family: NotoSans-BlackItalic
      fonts:
        - asset: assets/fonts/NotoSans/NotoSans-BlackItalic.ttf

